Zenmaster ver 1.5.3
SauceLLC/sauce4zwift-mod-store pull request #3
Opened 2024-11-16 22:21 UTC by Zenmaster28

+ Zenmaster ver 1.5.3

2024-11-16 22:24 UTC, mayfield requested changes
Can you update homeURL to something specific to your mod?

2024-11-16 22:25 UTC, mayfield requested changes
Oh and it's a nit, but the words "for S4Z" will be redundant in this context for mod name and description.

2024-11-17 11:25 UTC, Zenmaster28 commented
Changes made

2024-11-17 19:15 UTC, mayfield approved these changes

2024-11-17 19:15 UTC, merged